version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: strapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapi
    volumes:
      - postgres_/var/lib/postgresql/data
    networks:
      - strapi-network

  strapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: strapi_app
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
      DATABASE_SSL: false
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi-network
    command: ["tail", "-f", "/dev/null"]  # ADDED: Keeps container running for debugging

  nginx:
    image: nginx:alpine
    container_name: strapi_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-network

networks:
  strapi-network:
    driver: bridge

volumes:
  postgres_:
